version: '{build}'
os: Windows Server 2012
install:
  - cinst jdk8 -params 'installdir=C:\\jdk8'
  - SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - ps: $ErrorActionPreference = "Continue"
  - ps: scoop bucket add versions
  - ps: $ErrorActionPreference = "Stop"
  - ps: scoop install sbt0.13
environment:
  CI_SCALA_VERSION: 2.12.7
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: "-t7z -m0=lzma -mx=9"
build_script:
  - sbt version # dummy step, a build_script step is required by appveyor.
test_script:
  - sbt "-Djna.nosys=true" ci-windows
